name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: echo Hello, Build!
    - name: Run tests
      run: |
         xcodebuild test -project GithubActionTest.xcodeproj -scheme GithubActionTest -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=14.4'
         
